dist: trusty
sudo: false

branches:
  only:
    - master
    - dev
    
language: node_js

node_js:
  - "13"

addons:
  apt:
    sources:
      - mongodb-4.0-trusty
    packages:
      - mongodb-org-server
      
cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run coverage
          
