dist: trusty
sudo: false

branches:
  only:
    - master

language: node_js

node_js:
  - "13"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run coverage
          
