dist: bionic
sudo: false

branches:
  only:
    - master
    - dev
    
language: node_js

node_js:
  - "13"

addons:
  apt:
    sources:
      - mongodb-4.0-bionic
    packages:
      - mongodb-org-server
      - redis-server
      
cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ln -s /usr/bin/redis-server /usr/local/bin/redis-server
  - npm run coverage
          
